---
# THIS IS NOT A TEMPLATE.
# This is just for testing the repo itself.
# This calls the reusable workflow from its local file path.
name: Docker Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/linters/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/linters/**'

# cancel any previously-started, yet still active runs of this workflow on the same branch
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  call-docker-build:

    name: Call Docker Build

    uses: ./.github/workflows/reusable-docker-build.yaml

    permissions:
      contents: read
      packages: write
      pull-requests: write
    
    secrets:

      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}

      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

    with:
      
      dockerhub-enable: false
      ghcr-enable: true

      image-names: |
        ghcr.io/${{ github.repository }}
        
  generate-provenance:
    needs: call-docker-build
    name: Generate build provenance
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          path: artifact/
        
      - name: Show me file structure
        run: ls

      - name: Generate provenance
        uses: slsa-framework/github-actions-demo@v0.1
        with:
          artifact_path: artifact/
